FROM  debian:trixie-slim

RUN   useradd -ms /bin/bash runner

RUN   apt-get update --allow-releaseinfo-change && \
      apt-get install -y \
      curl \
      git \
      python-is-python3 \
      python3-pip \
      build-essential \
      cmake \
      wget \
      nano \
      jq \
      libusb-1.0-0-dev \
      ca-certificates \
      gnupg \
      && rm -rf /var/lib/apt/lists/*

RUN   python -m pip install gatorgrade --break-system-packages

# Create Directory for Arduino CLI
RUN mkdir -p /usr/local/bin

# Arduino CLI configuration
RUN curl -fsSL https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz \
| tar -xz -C /usr/local/bin --strip-components=1

# Make sure binary is executable 
RUN chmod +x /usr/local/bin/arduino-cli

# very installation
RUN /usr/local/bin/arduino-cli version

# Initialize Arduino CLI
RUN /usr/local/bin/arduino-cli config init

# Install Arduino Cores
RUN arduino-cli core update-index && \
    arduino-cli core install arduino:avr && \
    arduino-cli core install arduino:samd && \
    arduino-cli core install arduino:mbed_rp2040

RUN chown -R runner:runner /root/.arduino15

# Runner Setup
RUN mkdir -p /home/runner/actions-runner
RUN cd /home/runner/actions-runner && \
    curl -o actions-runner-linux-x64-2.330.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.330.0/actions-runner-linux-x64-2.330.0.tar.gz && \
    tar xzf ./actions-runner-linux-x64-2.330.0.tar.gz

ADD entrypoint-arduino.sh entrypoint-arduino.sh
RUN chmod +x entrypoint-arduino.sh

RUN chown runner:runner /home/runner -R
RUN chmod o+rws /home/runner -R

USER runner

ENTRYPOINT /entrypoint-arduino.sh