
name: Publish image
on:
  push:
    branches:
      - Arduino

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v3

# Log in to GHCR
      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

# Build and push Pico
      - name: Build Pico image
        run: |
          docker build -f Pico/Dockerfile.pico . -t gdbuddy-pico:latest

      - name: Publish Pico image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/gdbuddy:pico
          docker tag gdbuddy:pico:latest $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

# Build and push Arduino
      - name: Build Arduino image
        run: |
          docker build -f Arduino/Dockerfile.arduino . -t gdbuddy-arduino:latest

      - name: Publish Arduino image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/gdbuddy:arduino
          docker tag gdbuddy:arduino:latest $IMAGE_ID:latest
          docker push $IMAGE_ID:latest