
name: Publish image
on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
      - uses: actions/checkout@v3

# Log in to GHCR
      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

# Build and push Pico C
      - name: Build Pico image
        run: |
          docker build -t gdbuddy:pico-c ./Pico-C

      - name: Publish Pico image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/gdbuddy:pico-c
          docker tag gdbuddy:pico $IMAGE_ID
          docker push $IMAGE_ID

# Build and push Pico Micropython
      - name: Build Pico image
        run: |
          docker build -f . -t gdbuddy:pico-c ./Pico-Micropython

      - name: Publish Pico image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/gdbuddy:pico-c
          docker tag gdbuddy:pico $IMAGE_ID
          docker push $IMAGE_ID

# Build and push Arduino
      - name: Build Arduino image
        run: |
          docker build -t gdbuddy:arduino ./Arduino

      - name: Publish Arduino image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/gdbuddy:arduino
          docker tag gdbuddy:arduino $IMAGE_ID
          docker push $IMAGE_ID